<?php

/*
 * Editor server script for DB table publishers
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'publishers', 'id' )
	->fields(
		Field::inst( 'id' )
			->set( false )
			->validator( 'Validate::unique' ),
		Field::inst( 'publisher' )
			->validator( 'Validate::notEmpty' ),
		Field::inst( 'integration' )
			->validator( 'Validate::notEmpty' ),
		Field::inst( 'contact' )
			->validator( 'Validate::minLen', array( 'empty'=>false, 'min'=>10 ) ),
		Field::inst( 'status' )
			->validator( 'Validate::notEmpty' ),
		Field::inst( 'website' )
			->validator( 'Validate::url', array( 'empty' => false ) )
	)
	->process( $_POST )
	->json();