
-- 
-- Editor server script for DB table publishers
-- Automatically generated by http://editor.datatables.net/generator
-- 

CREATE TABLE `publishers` (
	`id` int(10) NOT NULL auto_increment,
	`publisher` varchar(255) default NULL,
	`integration` varchar(255) default NULL,
	`contact` varchar(255) default NULL,
	`status` varchar(255) default NULL,
	`website` varchar(255) default NULL,
	PRIMARY KEY  (`id`)
);

